### ISSUE TITLE
Réécriture en ES2015

### ISSUE THREAD

**Issue by njl07** [Valko54/node-config-manager#2]
Bonjour,

Afin d'avoir une cohérence accrue avec la nouvelle plateforme Node.JS >= 4.1.X, pouvez-vous migrer le code sur le langage ES2015?

Merci pour votre retour,

Cordialement.

**Comment by adetante** [comment]
:+1:

**Comment by adetante** [comment]
Est-ce qu'on pourra avoir une date à laquelle ça sera disponible ?

**Comment by Valko54** [comment]
Ce n'est pas prévu pour le moment.

Rencontrez-vous des problèmes de compatibilité avec la version actuelle ?

**Comment by njl07** [comment]
Pas de problème de compatibilité mais juste une sensation amère dans la bouche lors de l'examen du code car j'ai l'impression d'être à l'âge de pierre :)

**Comment by Valko54** [comment]
Je sais que la programmation orientée prototype peut être compliquée au premier abord. Mais avec un peu de persévérance et un bon tutoriel, ce n'est pas très éloigné de la programmation orientée objet que vous me proposez.

Voici quelques documents ressources afin de vous aider dans votre apprentissage:
* https://developer.mozilla.org/fr/docs/Web/JavaScript/H%C3%A9ritage_et_cha%C3%AEne_de_prototypes
* https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object/prototype
* http://stackoverflow.com/questions/310870/use-of-prototype-vs-this-in-javascript

Je peux aussi vous mettre en relation avec un ami (Clément S.) qui pourra vous accompagner dans votre périple.

**Comment by njl07** [comment]
Je vous remercie amplement pour tous ces guides qui me seront fort utiles.

Pour votre progression personnelle dans le monde des nouveaux langages, voici des liens utiles également:

* https://babeljs.io/docs/learn-es2015/
* https://nodejs.org/en/docs/es6/

A bon entendeur et bonne journée :)

**Comment by Valko54** [comment]
Merci à vous également,

Je clos cette issue et je m'ajoute un petit post-it dans un coin afin de ne pas oublier d'envisager une possible migration vers ES6 lors d'une future refonte, qui reste aujourd'hui, incertaine.

Bonne journée et bonne continuation.
