### ISSUE TITLE
Update Dependency debug to 2.2.0 

### ISSUE THREAD

**Issue by fr-kshibata** [Valko54/node-config-manager#4]
2.1.0 is vulnerable to regex attacks
<img width="1239" alt="security-vulnerability" src="https://cloud.githubusercontent.com/assets/13744098/12437428/256878a6-bf61-11e5-91d8-01d54bfec1f0.png">

**Comment by Valko54** [comment]
Oh my god ! Thank you, fr-kshibata.

I have not received any notification for your issue, sorry for the delay. I do this ASAP.

**Comment by Valko54** [comment]
It's done. 

node-config-manager@1.0.3

**Comment by fr-kshibata** [comment]
:+1:
